name = "gtkzero_fpm"
description = "A demo using gtk-fortran as a fpm dependency: an empty GTK window"
version = "4.2.0"
license = "MIT"
author = "Vincent Magnin"
maintainer = "https://github.com/vmagnin/gtkzero_fpm/issues"
copyright = "Copyright 2021, Vincent Magnin"
homepage = "https://github.com/vmagnin/gtkzero_fpm"
keywords = ["gtk-fortran"]

[dependencies]
gtk-fortran = { git = "https://github.com/vmagnin/gtk-fortran.git", branch = "experimental_fpm" }

[build]
link = [
  "gtk-4",
  "gio-2.0",
  "gobject-2.0",
  "glib-2.0" ]
# Depending of your project you may also need 
# to link to some of these libraries:
#  "pangocairo-1.0",
#  "pango-1.0",
#  "gdk_pixbuf-2.0",
#  "cairo-gobject",
#  "cairo",
#  "graphene-1.0",
#  "harfbuzz",
#  "vulkan"...

