name = "gtkzero_fpm"
description = "A demo using gtk-fortran as a fpm dependency"
version = "4.2.0"
license = "MIT"
author = "Vincent Magnin"
maintainer = "Vincent Magnin"
copyright = "Copyright 2021, Vincent Magnin"
homepage = "https://github.com/vmagnin/gtkzero_fpm"
keywords = ["gtk-fortran"]

[dependencies]
gtk-4-fortran = { git = "https://github.com/vmagnin/gtk-fortran.git", branch = "experimental_fpm" }

[build]
link = [
  "gtk-4",
  "pangocairo-1.0",
  "pango-1.0",
  "harfbuzz",
  "gdk_pixbuf-2.0",
  "cairo-gobject",
  "cairo",
  "graphene-1.0",
  "gio-2.0",
  "gobject-2.0",
  "glib-2.0" ]
