name = "gtkzero_fpm"
version = "4.0.0"
license = "GPL v3"
author = "Vincent Magnin"
maintainer = "Vincent Magnin"
copyright = "Copyright 2021, Vincent Magnin"

[build]
link = [
  "gtk-4",
  "pangocairo-1.0",
  "pango-1.0",
  "harfbuzz",
  "gdk_pixbuf-2.0",
  "cairo-gobject",
  "cairo",
  "graphene-1.0",
  "gio-2.0",
  "gobject-2.0",
  "glib-2.0",
  "gtk-4-fortran" ]
external-modules = ["gtk", "g"]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false
